name: Build and Deploy

on:
  push:
    branches: ["main"]

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/distant-bot:latest

  deploy:
    needs: docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: 1.64.0 # Utilisation d'une version fixe plutôt que 'latest' pour éviter les bugs de shasum
          
      - name: Deploy to VPS
        run: |
          # Utilisation de l'outil CLI natif vu que l'action github l'a déjà installé et lancé un daemon
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=github-runner --accept-routes --reset

          # Utilisation de netcat pour forcer le traçage si besoin (souvent facultatif avec le daemon system global)
          sudo apt-get update && sudo apt-get install -y netcat-openbsd

          # Création du dossier et copie du docker-compose.yml via l'IP Tailscale du VPS
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "mkdir -p /home/${{ secrets.SERVER_USER }}/distant-bot"
          scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/distant-bot/docker-compose.yml
          
          # Re-déploiement sur le VPS en injectant la variable d'environnement
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd /home/${{ secrets.SERVER_USER }}/distant-bot && export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} && docker compose down && docker compose pull && docker compose up -d"
